// <auto-generated />
namespace SystemMartinezCV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class generos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(generos));
        
        string IMigrationMetadata.Id
        {
            get { return "202002100750071_generos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
