// <auto-generated />
namespace SystemMartinezCV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ptm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ptm));
        
        string IMigrationMetadata.Id
        {
            get { return "202002171410290_ptm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
